<?php

/**
 * OnPay Magento2 module
 *
 * @category  Payment_Method
 * @package   OnPay_Magento2
 * @copyright OnPay
 *
 * @magento-module
 * Plugin Name: OnPay Magento2
 * Plugin URI: https://onpay.io
 * Description: Collect payments using OnPay.io as PSP
 * Author URI: https://onpay.io
 */

/**
 * @var \OnPay\Magento2\Block\RedirectUrl $block
 */
?>
<?php if (null !== $block->getPaymentUrl()): ?>
    <?php header("Location: " .  $block->getPaymentUrl()); exit(); ?>
<?php elseif (null === $block->getOrderId()): ?>
    <h3><?= $block->escapeHtml(__('Could not get OrderID')); ?></h3>
<?php elseif ($block->isAlreadyPaid()): ?>
    <h3><?= $block->escapeHtml(__('This order has already been processed')); ?></h3>
    <p><?= $block->escapeHtml(__('Order ID: %s', $block->getOrderId()));?></p>
<?php else: ?>
    <h3><?= $block->escapeHtml(__('Payment window is not configured correct')); ?></h3>
<?php endif; ?>

