<?php
/**
 * @var \OnPay\Magento2\Block\RedirectUrl $block
 */
?>

<?php if ($block->isValid()): ?>
    <form id="onpay_window_form" method="post" action="<?= $block->getActionUrl(); ?>" accept-charset="UTF-8">
        <?php foreach ($block->getFormFields() as $key => $value): ?>
            <input type="hidden" name="<?= $block->escapeHtml($key); ?>" value="<?= $block->escapeHtml($value); ?>">
        <?php endforeach; ?>

        <input type="submit" style="display:none;" value="Make Payment">
    </form>
<?php else: ?>
    <h1>Payment window is not configured correct</h1>
<?php endif; ?>

<script type="text/javascript">
    require([
        'jquery'
    ], function($) {
        'use strict';
        $('#onpay_window_form').submit();
    });
</script>