<?php

/**
 * OnPay Magento2 module
 *
 * @category  Payment_Method
 * @package   OnPay_Magento2
 * @copyright OnPay
 *
 * @magento-module
 * Plugin Name: OnPay Magento2
 * Plugin URI: https://onpay.io
 * Description: Collect payments using OnPay.io as PSP
 * Version: 1.0.0
 * Author URI: https://onpay.io
 */

?>
<?php
$key = $block->getRequest()->getParam('key');
$controller = $block->getCustomUrl();
echo $block->getButtonHtml();
?>
<script>
    require([
        'jquery',
        'prototype'
    ], function(jQuery) {
        jQuery('#btn_id').click(function() {
            // window.open('/onpay/auth/index', '_blank');
            window.location.href = '/onpay/auth/index/key/<?= $block->escapeUrl($key) ?>';
        });
    });
</script>