<?php

/**
 * OnPay Magento2 module
 *
 * @category  Payment_Method
 * @package   Onpay_Magento
 * @author    Julian F. Christmas <jc@intelligodenmark.dk>
 * @copyright 2022 Team.blue Denmark A/S
 * @license   GPL-2.0+
 *
 * @magento-module
 * Plugin Name: OnPay Magento2
 * Plugin URI: https://onpay.io
 * Description: Collect payments using OnPay.io as PSP
 * Author: Julian F. Christmas
 * Version: 1.0.0
 * Author URI: https://intelligodenmark.dk
 */
?>
<?php
$key = $block->getRequest()->getParam('key');
$controller = $block->getCustomUrl();
echo $block->getButtonHtml();
?>
<script>
    require([
        'jquery',
        'prototype'
    ], function(jQuery) {
        jQuery('#btn_id').click(function() {
            // window.open('/onpay/auth/index', '_blank');
            window.location.href = '/onpay/auth/index/key/<?= $block->escapeUrl($key) ?>';
        });
    });
</script>